name: CI

# Controls when the action will run. Triggers the workflow on push events
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2
    
    # Sets up a Python environment
    - uses: actions/setup-python@v2
      with:
          python-version: 3.7

    # Sets up a Poetry
    - uses: Gr1N/setup-poetry@v2

    # Runs a set of commands using the runners shell
    - name: Shows versions
      run: |
        python --version
        pip --version
        poetry --version

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: poetry update
